# 是否爬取全部城市，是则 true 不是则false 
IsAll=false
# 分页跳转等待时间，不宜过小，容易被检测到
Sleep=30

# 当IsAll 为 false是要爬取的城市
[[Cites]]
Name="昆明"
Url="https://km.anjuke.com/"
[[Cites]]
Name="普洱"
Url="https://puer.anjuke.com/"
[[Cites]]
Name="丽江"
Url="https://lijiang.anjuke.com/"
[[Cites]]
Name="大理"
Url="https://dali.anjuke.com/"
[[Cites]]
Name="西双版纳"
Url="https://bannan.anjuke.com/"
[[Cites]]
Name="曲靖"
Url="https://qujing.anjuke.com/"
[[Cites]]
Name="昭通"
Url="https://zhaotong.anjuke.com/"
[[Cites]]
Name="保山"
Url="https://baoshan.anjuke.com/"
[[Cites]]
Name="文山"
Url="https://wenshan.anjuke.com/"
[[Cites]]
Name="临沧"
Url="https://lingcang.anjuke.com/"
[[Cites]]
Name="德宏"
Url="https://dehong.anjuke.com/"
[[Cites]]
Name="怒江"
Url="https://nujiang.anjuke.com/"
[[Cites]]
Name="迪庆"
Url="https://diqing.anjuke.com/"
[[Cites]]
Name="楚雄"
Url="https://chuxiong.anjuke.com/"
[[Cites]]
Name="红河"
Url="https://honghe.anjuke.com/"
[[Cites]]
Name="玉溪"
Url="https://yuxi.anjuke.com/"
